<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '+ Horse add' => '+ Horse add',
    'Account number 1' => 'Account number 1',
    'Account number 2' => 'Account number 2',
    'Account type' => 'Account type',
    'Account type 1' => 'Account type 1',
    'Account type 2' => 'Account type 2',
    'Active' => 'Active',
    'Add' => 'Add',
    'Additional address data' => 'Additional address data',
    'Additional info' => 'Additional info',
    'Arrival date' => 'Arrival date',
    'Banking code 1' => 'Banking code 1',
    'Banking code 2' => 'Banking code 2',
    'Birth date' => 'Birth date',
    'Box name' => 'Box name',
    'Box number' => 'Box number',
    'Boxes' => 'Boxes',
    'City' => 'City',
    'Client' => 'Client',
    'Client data' => 'Client data',
    'Clients' => 'Clients',
    'Color' => 'Color',
    'Contract number' => 'Contract number',
    'Coupler' => 'Coupler',
    'Date' => 'Date',
    'Departure date' => 'Departure date',
    'Email' => 'Email',
    'Employees' => 'Employees',
    'End date' => 'End date',
    'Fax' => 'Fax',
    'Female' => 'Female',
    'First name' => 'First name',
    'Horse' => 'Horse',
    'HorseName' => 'Horse name',
    'Horses' => 'Horses',
    'Information' => 'Information',
    'Last name' => 'Last name',
    'Male' => 'Male',
    'Medicament' => 'Medicament',
    'Mob.phone' => 'Mob.phone',
    'Name' => 'Name',
    'Note' => 'Note',
    'Online number' => 'Online number',
    'Open stall' => 'Open stall',
    'Other notes about client ...' => 'Other notes about client ...',
    'Owner 1' => 'Owner 1',
    'Owner 2' => 'Owner 2',
    'Performed by' => 'Performed by',
    'Phone' => 'Phone',
    'Plannings' => 'Plannings',
    'Price' => 'Price',
    'Saving data error' => 'Saving data error',
    'Service name' => 'Service name',
    'Services' => 'Services',
    'Settings' => 'Settings',
    'Sex' => 'Sex',
    'Smith' => 'Smith',
    'Stall' => 'Stall',
    'Start date' => 'Start date',
    'Street' => 'Street',
    'Suppliers' => 'Suppliers',
    'The requested page does not exist.' => 'The requested page does not exist.',
    'Vet' => 'Vet',
    'Zip code' => 'Zip code',
    'Home' => 'Home',
    'Demo App' => 'Demo Application',
    'id' => 'id',
];
