<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '+ Horse add' => '+ Pferd hinzufügen',
    'Account number 1' => 'Konto 1',
    'Account number 2' => 'Konto 2',
    'Account type' => 'Konto',
    'Account type 1' => 'Bezeichung Konto 1',
    'Account type 2' => 'Bezeichung Konto 2',
    'Active' => 'Aktiv',
    'Add' => 'Hinzufügen',
    'Additional address data' => 'Adresszusatz',
    'Additional info' => 'Zusätzliche Information',
    'Arrival date' => 'Zugang',
    'Banking code 1' => 'BLZ 1',
    'Banking code 2' => 'BLZ 2',
    'Birth date' => 'Geburtstag',
    'Box name' => 'Box',
    'Box number' => 'Boxnummer',
    'Boxes' => 'Boxen',
    'City' => 'Ort',
    'Client' => 'Kunde',
    'Client data' => 'Kundendaten',
    'Clients' => 'Kunden',
    'Color' => 'Farbe',
    'Contract number' => 'Vertragsnummer',
    'Coupler' => 'Koppel',
    'Date' => 'Datum',
    'Departure date' => 'Abgang',
    'Email' => 'Email',
    'Employees' => 'Mitarbeiter',
    'End date' => 'bis',
    'Fax' => 'Fax',
    'Female' => 'Weiblich',
    'First name' => 'Vorname',
    'Horse' => 'Pferd',
    'HorseName' => 'Name des Pferdes',
    'Horses' => 'Pferde',
    'Information' => 'Stammdaten',
    'Last name' => 'Nachname',
    'Male' => 'Männlich',
    'Medicament' => 'Medikament',
    'Mob.phone' => 'Handy',
    'Name' => 'Name',
    'Note' => 'Bemerkung',
    'Online number' => 'Lebensnummer',
    'Open stall' => 'Offenstall',
    'Other notes about client ...' => 'Sonstige Anmerkungen zum Kunden ...',
    'Owner 1' => 'Inhaber 1',
    'Owner 2' => 'Inhaber 2',
    'Performed by' => 'Bereiter',
    'Phone' => 'Tel',
    'Plannings' => 'Behandlungsplanung',
    'Price' => 'Preis',
    'Saving data error' => 'Fehler beim Speichern der Daten',
    'Service name' => 'Dienstleistung',
    'Services' => 'Dienstleistungen',
    'Settings' => 'Einstellungen',
    'Sex' => 'Geschlecht',
    'Smith' => 'Hufschmied',
    'Stall' => 'Stall',
    'Start date' => 'von',
    'Street' => 'Strasse',
    'Suppliers' => 'Lieferanten',
    'The requested page does not exist.' => 'Die angeforderte Seite existiert nicht.',
    'Vet' => 'Tierarzt',
    'Zip code' => 'PLZ',
    'Home' => 'Hauptseite',
    'Demo App' => 'Demo Anwendung',
    'id' => 'id',
];
